def failure(self):
    return self.__failure
